// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // Alliances
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Alliance
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Guilds where [Guilds].[AllianceId] point to this entity (FK_Guilds_Alliances)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Guild> Guilds { get; set; } // Guilds.FK_Guilds_Alliances

        public Alliance()
        {
            Guilds = new System.Collections.Generic.List<Guild>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
