// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // CharacterSynergies
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class CharacterSynergy
    {
        public int Id { get; set; } // Id (Primary key)
        public int PrimaryCharacterId { get; set; } // PrimaryCharacterId
        public int SynergyCharacterId { get; set; } // SynergyCharacterId
        public int SynergyTypeId { get; set; } // SynergyTypeId
        public string Reason { get; set; } // Reason (length: 5000)

        // Foreign keys

        /// <summary>
        /// Parent SynergyType pointed by [CharacterSynergies].([SynergyTypeId]) (FK_CharacterSynergies_SynergyTypes)
        /// </summary>
        public virtual SynergyType SynergyType { get; set; } // FK_CharacterSynergies_SynergyTypes

        /// <summary>
        /// Parent Unit pointed by [CharacterSynergies].([PrimaryCharacterId]) (FK_CharacterSynergies_Units)
        /// </summary>
        public virtual Unit PrimaryCharacter { get; set; } // FK_CharacterSynergies_Units

        /// <summary>
        /// Parent Unit pointed by [CharacterSynergies].([SynergyCharacterId]) (FK_CharacterSynergies_Units1)
        /// </summary>
        public virtual Unit SynergyCharacter { get; set; } // FK_CharacterSynergies_Units1

        public CharacterSynergy()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
