// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // Guilds
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Guild
    {
        public int Id { get; set; } // Id (Primary key)
        public int AllianceId { get; set; } // AllianceId
        public long SwgohGgId { get; set; } // SwgohGgId
        public string SwgohGgUrl { get; set; } // SwgohGgUrl (length: 50)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Players where [Players].[GuildId] point to this entity (FK_Players_Guilds)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Player> Players { get; set; } // Players.FK_Players_Guilds

        // Foreign keys

        /// <summary>
        /// Parent Alliance pointed by [Guilds].([AllianceId]) (FK_Guilds_Alliances)
        /// </summary>
        public virtual Alliance Alliance { get; set; } // FK_Guilds_Alliances

        public Guild()
        {
            Players = new System.Collections.Generic.List<Player>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
