// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // ModStatUnits
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class ModStatUnit
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child PlayerMods where [PlayerMods].[PrimaryUnitsId] point to this entity (FK_PlayerMods_ModStatUnits)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerMod> PrimaryUnits { get; set; } // PlayerMods.FK_PlayerMods_ModStatUnits
        /// <summary>
        /// Child PlayerMods where [PlayerMods].[Secondary1UnitsId] point to this entity (FK_PlayerMods_ModStatUnits1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerMod> Secondary1Units { get; set; } // PlayerMods.FK_PlayerMods_ModStatUnits1
        /// <summary>
        /// Child PlayerMods where [PlayerMods].[Secondary2UnitsId] point to this entity (FK_PlayerMods_ModStatUnits2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerMod> Secondary2Units { get; set; } // PlayerMods.FK_PlayerMods_ModStatUnits2
        /// <summary>
        /// Child PlayerMods where [PlayerMods].[Secondary3UnitsId] point to this entity (FK_PlayerMods_ModStatUnits3)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerMod> Secondary3Units { get; set; } // PlayerMods.FK_PlayerMods_ModStatUnits3
        /// <summary>
        /// Child PlayerMods where [PlayerMods].[Secondary4UnitsId] point to this entity (FK_PlayerMods_ModStatUnits4)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerMod> Secondary4Units { get; set; } // PlayerMods.FK_PlayerMods_ModStatUnits4

        public ModStatUnit()
        {
            PrimaryUnits = new System.Collections.Generic.List<PlayerMod>();
            Secondary1Units = new System.Collections.Generic.List<PlayerMod>();
            Secondary2Units = new System.Collections.Generic.List<PlayerMod>();
            Secondary3Units = new System.Collections.Generic.List<PlayerMod>();
            Secondary4Units = new System.Collections.Generic.List<PlayerMod>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
