// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // PlayerCharacters
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class PlayerCharacterConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PlayerCharacter>
    {
        public PlayerCharacterConfiguration()
            : this("dbo")
        {
        }

        public PlayerCharacterConfiguration(string schema)
        {
            ToTable("PlayerCharacters", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PlayerId).HasColumnName(@"PlayerId").HasColumnType("int").IsRequired();
            Property(x => x.UnitId).HasColumnName(@"UnitId").HasColumnType("int").IsRequired();
            Property(x => x.Level).HasColumnName(@"Level").HasColumnType("int").IsRequired();
            Property(x => x.Stars).HasColumnName(@"Stars").HasColumnType("int").IsRequired();
            Property(x => x.Gear).HasColumnName(@"Gear").HasColumnType("int").IsRequired();
            Property(x => x.Power).HasColumnName(@"Power").HasColumnType("bigint").IsRequired();

            // Foreign keys
            HasRequired(a => a.Player).WithMany(b => b.PlayerCharacters).HasForeignKey(c => c.PlayerId).WillCascadeOnDelete(false); // FK_PlayerCharacters_Players
            HasRequired(a => a.Unit).WithMany(b => b.PlayerCharacters).HasForeignKey(c => c.UnitId).WillCascadeOnDelete(false); // FK_PlayerCharacters_Units
        }
    }

}
// </auto-generated>
