// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // PlayerMods
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class PlayerMod
    {
        public int Id { get; set; } // Id (Primary key)
        public int PlayerId { get; set; } // PlayerId
        public int? PlayerCharacterId { get; set; } // PlayerCharacterId
        public string SwgohGgId { get; set; } // SwgohGgId (length: 150)
        public int Pips { get; set; } // Pips
        public int SlotId { get; set; } // SlotId
        public int SetId { get; set; } // SetId
        public int PrimaryTypeId { get; set; } // PrimaryTypeId
        public int PrimaryUnitsId { get; set; } // PrimaryUnitsId
        public decimal PrimaryValue { get; set; } // PrimaryValue
        public int Secondary1TypeId { get; set; } // Secondary1TypeId
        public int Secondary1UnitsId { get; set; } // Secondary1UnitsId
        public decimal Secondary1Value { get; set; } // Secondary1Value
        public int Secondary2TypeId { get; set; } // Secondary2TypeId
        public int Secondary2UnitsId { get; set; } // Secondary2UnitsId
        public decimal Secondary2Value { get; set; } // Secondary2Value
        public int Secondary3TypeId { get; set; } // Secondary3TypeId
        public int Secondary3UnitsId { get; set; } // Secondary3UnitsId
        public decimal Secondary3Value { get; set; } // Secondary3Value
        public int Secondary4TypeId { get; set; } // Secondary4TypeId
        public int Secondary4UnitsId { get; set; } // Secondary4UnitsId
        public decimal Secondary4Value { get; set; } // Secondary4Value

        // Reverse navigation

        /// <summary>
        /// Child PlayerModSets where [PlayerModSets].[Mod1Id] point to this entity (FK_PlayerModSets_PlayerMods)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerModSet> Mod1 { get; set; } // PlayerModSets.FK_PlayerModSets_PlayerMods
        /// <summary>
        /// Child PlayerModSets where [PlayerModSets].[Mod2Id] point to this entity (FK_PlayerModSets_PlayerMods1)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerModSet> Mod2 { get; set; } // PlayerModSets.FK_PlayerModSets_PlayerMods1
        /// <summary>
        /// Child PlayerModSets where [PlayerModSets].[Mod3Id] point to this entity (FK_PlayerModSets_PlayerMods2)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerModSet> Mod3 { get; set; } // PlayerModSets.FK_PlayerModSets_PlayerMods2
        /// <summary>
        /// Child PlayerModSets where [PlayerModSets].[Mod4Id] point to this entity (FK_PlayerModSets_PlayerMods3)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerModSet> Mod4 { get; set; } // PlayerModSets.FK_PlayerModSets_PlayerMods3
        /// <summary>
        /// Child PlayerModSets where [PlayerModSets].[Mod5Id] point to this entity (FK_PlayerModSets_PlayerMods4)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerModSet> Mod5 { get; set; } // PlayerModSets.FK_PlayerModSets_PlayerMods4
        /// <summary>
        /// Child PlayerModSets where [PlayerModSets].[Mod6Id] point to this entity (FK_PlayerModSets_PlayerMods5)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerModSet> Mod6 { get; set; } // PlayerModSets.FK_PlayerModSets_PlayerMods5

        // Foreign keys

        /// <summary>
        /// Parent ModSet pointed by [PlayerMods].([SetId]) (FK_PlayerMods_ModSets)
        /// </summary>
        public virtual ModSet ModSet { get; set; } // FK_PlayerMods_ModSets

        /// <summary>
        /// Parent ModSlot pointed by [PlayerMods].([SlotId]) (FK_PlayerMods_ModSlots)
        /// </summary>
        public virtual ModSlot ModSlot { get; set; } // FK_PlayerMods_ModSlots

        /// <summary>
        /// Parent ModStatType pointed by [PlayerMods].([PrimaryTypeId]) (FK_PlayerMods_ModStatTypes)
        /// </summary>
        public virtual ModStatType PrimaryType { get; set; } // FK_PlayerMods_ModStatTypes

        /// <summary>
        /// Parent ModStatType pointed by [PlayerMods].([Secondary1TypeId]) (FK_PlayerMods_ModStatTypes1)
        /// </summary>
        public virtual ModStatType Secondary1Type { get; set; } // FK_PlayerMods_ModStatTypes1

        /// <summary>
        /// Parent ModStatType pointed by [PlayerMods].([Secondary2TypeId]) (FK_PlayerMods_ModStatTypes2)
        /// </summary>
        public virtual ModStatType Secondary2Type { get; set; } // FK_PlayerMods_ModStatTypes2

        /// <summary>
        /// Parent ModStatType pointed by [PlayerMods].([Secondary3TypeId]) (FK_PlayerMods_ModStatTypes3)
        /// </summary>
        public virtual ModStatType Secondary3Type { get; set; } // FK_PlayerMods_ModStatTypes3

        /// <summary>
        /// Parent ModStatType pointed by [PlayerMods].([Secondary4TypeId]) (FK_PlayerMods_ModStatTypes4)
        /// </summary>
        public virtual ModStatType Secondary4Type { get; set; } // FK_PlayerMods_ModStatTypes4

        /// <summary>
        /// Parent ModStatUnit pointed by [PlayerMods].([PrimaryUnitsId]) (FK_PlayerMods_ModStatUnits)
        /// </summary>
        public virtual ModStatUnit PrimaryUnits { get; set; } // FK_PlayerMods_ModStatUnits

        /// <summary>
        /// Parent ModStatUnit pointed by [PlayerMods].([Secondary1UnitsId]) (FK_PlayerMods_ModStatUnits1)
        /// </summary>
        public virtual ModStatUnit Secondary1Units { get; set; } // FK_PlayerMods_ModStatUnits1

        /// <summary>
        /// Parent ModStatUnit pointed by [PlayerMods].([Secondary2UnitsId]) (FK_PlayerMods_ModStatUnits2)
        /// </summary>
        public virtual ModStatUnit Secondary2Units { get; set; } // FK_PlayerMods_ModStatUnits2

        /// <summary>
        /// Parent ModStatUnit pointed by [PlayerMods].([Secondary3UnitsId]) (FK_PlayerMods_ModStatUnits3)
        /// </summary>
        public virtual ModStatUnit Secondary3Units { get; set; } // FK_PlayerMods_ModStatUnits3

        /// <summary>
        /// Parent ModStatUnit pointed by [PlayerMods].([Secondary4UnitsId]) (FK_PlayerMods_ModStatUnits4)
        /// </summary>
        public virtual ModStatUnit Secondary4Units { get; set; } // FK_PlayerMods_ModStatUnits4

        /// <summary>
        /// Parent Player pointed by [PlayerMods].([PlayerId]) (FK_PlayerMods_Players)
        /// </summary>
        public virtual Player Player { get; set; } // FK_PlayerMods_Players

        /// <summary>
        /// Parent PlayerCharacter pointed by [PlayerMods].([PlayerCharacterId]) (FK_PlayerMods_PlayerCharacters)
        /// </summary>
        public virtual PlayerCharacter PlayerCharacter { get; set; } // FK_PlayerMods_PlayerCharacters

        public PlayerMod()
        {
            PrimaryTypeId = 0;
            PrimaryUnitsId = 0;
            Secondary1TypeId = 0;
            Secondary1UnitsId = 0;
            Secondary2TypeId = 0;
            Secondary2UnitsId = 0;
            Secondary3TypeId = 0;
            Secondary3UnitsId = 0;
            Secondary4TypeId = 0;
            Secondary4UnitsId = 0;
            Mod1 = new System.Collections.Generic.List<PlayerModSet>();
            Mod2 = new System.Collections.Generic.List<PlayerModSet>();
            Mod3 = new System.Collections.Generic.List<PlayerModSet>();
            Mod4 = new System.Collections.Generic.List<PlayerModSet>();
            Mod5 = new System.Collections.Generic.List<PlayerModSet>();
            Mod6 = new System.Collections.Generic.List<PlayerModSet>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
