// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // Players
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Player
    {
        public int Id { get; set; } // Id (Primary key)
        public int GuildId { get; set; } // GuildId
        public string InGameName { get; set; } // InGameName (length: 50)
        public string SwgohGgName { get; set; } // SwgohGgName (length: 50)
        public string SwgohGgUrl { get; set; } // SwgohGgUrl (length: 100)
        public bool CollectionSyncEnabled { get; set; } // CollectionSyncEnabled
        public System.DateTime LastCollectionSync { get; set; } // LastCollectionSync
        public bool ModSyncEnabled { get; set; } // ModSyncEnabled
        public System.DateTime LastModSync { get; set; } // LastModSync

        // Reverse navigation

        /// <summary>
        /// Child PlayerCharacters where [PlayerCharacters].[PlayerId] point to this entity (FK_PlayerCharacters_Players)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerCharacter> PlayerCharacters { get; set; } // PlayerCharacters.FK_PlayerCharacters_Players
        /// <summary>
        /// Child PlayerMods where [PlayerMods].[PlayerId] point to this entity (FK_PlayerMods_Players)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerMod> PlayerMods { get; set; } // PlayerMods.FK_PlayerMods_Players
        /// <summary>
        /// Child PlayerModSets where [PlayerModSets].[PlayerId] point to this entity (FK_PlayerModSets_Players)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<PlayerModSet> PlayerModSets { get; set; } // PlayerModSets.FK_PlayerModSets_Players

        // Foreign keys

        /// <summary>
        /// Parent Guild pointed by [Players].([GuildId]) (FK_Players_Guilds)
        /// </summary>
        public virtual Guild Guild { get; set; } // FK_Players_Guilds

        public Player()
        {
            CollectionSyncEnabled = true;
            LastCollectionSync = System.DateTime.UtcNow;
            ModSyncEnabled = false;
            LastModSync = System.DateTime.UtcNow;
            PlayerCharacters = new System.Collections.Generic.List<PlayerCharacter>();
            PlayerMods = new System.Collections.Generic.List<PlayerMod>();
            PlayerModSets = new System.Collections.Generic.List<PlayerModSet>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
