// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // PlayerCharacters
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class PlayerCharacter
    {
        public int Id { get; set; } // Id (Primary key)
        public int PlayerId { get; set; } // PlayerId
        public int UnitId { get; set; } // UnitId
        public int Level { get; set; } // Level
        public int Stars { get; set; } // Stars
        public int Gear { get; set; } // Gear
        public long Power { get; set; } // Power

        // Foreign keys

        /// <summary>
        /// Parent Player pointed by [PlayerCharacters].([PlayerId]) (FK_PlayerCharacters_Players)
        /// </summary>
        public virtual Player Player { get; set; } // FK_PlayerCharacters_Players

        /// <summary>
        /// Parent Unit pointed by [PlayerCharacters].([UnitId]) (FK_PlayerCharacters_Units)
        /// </summary>
        public virtual Unit Unit { get; set; } // FK_PlayerCharacters_Units
    }

}
// </auto-generated>
