// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // PlayerModSets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class PlayerModSetConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PlayerModSet>
    {
        public PlayerModSetConfiguration()
            : this("dbo")
        {
        }

        public PlayerModSetConfiguration(string schema)
        {
            ToTable("PlayerModSets", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PlayerId).HasColumnName(@"PlayerId").HasColumnType("int").IsRequired();
            Property(x => x.Mod1Id).HasColumnName(@"Mod1Id").HasColumnType("int").IsRequired();
            Property(x => x.Mod2Id).HasColumnName(@"Mod2Id").HasColumnType("int").IsRequired();
            Property(x => x.Mod3Id).HasColumnName(@"Mod3Id").HasColumnType("int").IsRequired();
            Property(x => x.Mod4Id).HasColumnName(@"Mod4Id").HasColumnType("int").IsRequired();
            Property(x => x.Mod5Id).HasColumnName(@"Mod5Id").HasColumnType("int").IsRequired();
            Property(x => x.Mod6Id).HasColumnName(@"Mod6Id").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Mod1).WithMany(b => b.Mod1).HasForeignKey(c => c.Mod1Id).WillCascadeOnDelete(false); // FK_PlayerModSets_PlayerMods1
            HasRequired(a => a.Mod2).WithMany(b => b.Mod2).HasForeignKey(c => c.Mod2Id).WillCascadeOnDelete(false); // FK_PlayerModSets_PlayerMods2
            HasRequired(a => a.Mod3).WithMany(b => b.Mod3).HasForeignKey(c => c.Mod3Id).WillCascadeOnDelete(false); // FK_PlayerModSets_PlayerMods3
            HasRequired(a => a.Mod4).WithMany(b => b.Mod4).HasForeignKey(c => c.Mod4Id).WillCascadeOnDelete(false); // FK_PlayerModSets_PlayerMods4
            HasRequired(a => a.Mod5).WithMany(b => b.Mod5).HasForeignKey(c => c.Mod5Id).WillCascadeOnDelete(false); // FK_PlayerModSets_PlayerMods5
            HasRequired(a => a.Mod6).WithMany(b => b.Mod6).HasForeignKey(c => c.Mod6Id).WillCascadeOnDelete(false); // FK_PlayerModSets_PlayerMods6
            HasRequired(a => a.Player).WithMany(b => b.PlayerModSets).HasForeignKey(c => c.PlayerId); // FK_PlayerModSets_Players
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
