// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // PlayerModSets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class PlayerModSet
    {
        public int Id { get; set; } // Id (Primary key)
        public int PlayerId { get; set; } // PlayerId
        public int Mod1Id { get; set; } // Mod1Id
        public int Mod2Id { get; set; } // Mod2Id
        public int Mod3Id { get; set; } // Mod3Id
        public int Mod4Id { get; set; } // Mod4Id
        public int Mod5Id { get; set; } // Mod5Id
        public int Mod6Id { get; set; } // Mod6Id

        // Foreign keys

        /// <summary>
        /// Parent Player pointed by [PlayerModSets].([PlayerId]) (FK_PlayerModSets_Players)
        /// </summary>
        public virtual Player Player { get; set; } // FK_PlayerModSets_Players

        /// <summary>
        /// Parent PlayerMod pointed by [PlayerModSets].([Mod1Id]) (FK_PlayerModSets_PlayerMods1)
        /// </summary>
        public virtual PlayerMod Mod1 { get; set; } // FK_PlayerModSets_PlayerMods1

        /// <summary>
        /// Parent PlayerMod pointed by [PlayerModSets].([Mod2Id]) (FK_PlayerModSets_PlayerMods2)
        /// </summary>
        public virtual PlayerMod Mod2 { get; set; } // FK_PlayerModSets_PlayerMods2

        /// <summary>
        /// Parent PlayerMod pointed by [PlayerModSets].([Mod3Id]) (FK_PlayerModSets_PlayerMods3)
        /// </summary>
        public virtual PlayerMod Mod3 { get; set; } // FK_PlayerModSets_PlayerMods3

        /// <summary>
        /// Parent PlayerMod pointed by [PlayerModSets].([Mod4Id]) (FK_PlayerModSets_PlayerMods4)
        /// </summary>
        public virtual PlayerMod Mod4 { get; set; } // FK_PlayerModSets_PlayerMods4

        /// <summary>
        /// Parent PlayerMod pointed by [PlayerModSets].([Mod5Id]) (FK_PlayerModSets_PlayerMods5)
        /// </summary>
        public virtual PlayerMod Mod5 { get; set; } // FK_PlayerModSets_PlayerMods5

        /// <summary>
        /// Parent PlayerMod pointed by [PlayerModSets].([Mod6Id]) (FK_PlayerModSets_PlayerMods6)
        /// </summary>
        public virtual PlayerMod Mod6 { get; set; } // FK_PlayerModSets_PlayerMods6

        public PlayerModSet()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
