// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Zelus.Data
{

    // SynergyTypes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class SynergyType
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child CharacterSynergies where [CharacterSynergies].[SynergyTypeId] point to this entity (FK_CharacterSynergies_SynergyTypes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CharacterSynergy> CharacterSynergies { get; set; } // CharacterSynergies.FK_CharacterSynergies_SynergyTypes

        public SynergyType()
        {
            CharacterSynergies = new System.Collections.Generic.List<CharacterSynergy>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
