// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace GuildRosterAnalyzer.Data
{

    public class GraDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<GraDbContext>
    {
        public GraDbContext Create()
        {
            return new GraDbContext();
        }
    }
}
// </auto-generated>
